package:
  name: "tupa"
  version: "v1.5.0"

source:
  git_rev: v1.5.0
  git_url: https://github.com/mdpoleto/tupa

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - MDAnalysis>=2.0
    - configparser
    - numpy>=1.2

about:
  home: https://github.com/mdpoleto/tupa
  license: GPLv3
  license_familY: GNU
  license_file: LICENSE
  summary: "Electric field analyses for molecular simulations."

extra:
  recipe-maintainers:
    - mdpoleto
