package:
  name: "tupa"
  version: "v1.5.0"

source:
  git_rev: v1.5.0
  git_url: https://github.com/mdpoleto/tupa

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools
  run:
    - mdanalysis>=2.0
    - numpy>=1.2
    - configparser
    - argparse

test:
  imports:
    - mdanalysis

about:
  home: https://mdpoleto.github.io/tupa/
  license: GPLv3
  license_familY: GNU
  license_file: LICENSE
  summary: "Electric field analyses for molecular simulations."

extra:
  recipe-maintainers:
    - mdpoleto
